### ISSUE TITLE
[Suggestion] Submod Updater support

### ISSUE THREAD

**Issue by zwartkop2** [DrakeTheDuelist/MAS-AprilFirst#2]
Probably not high priority, but could it be possible to add support for the Submod Updater by Booplicate to this submod and/or the Dreams and Nightmares submod?

**Comment by wboorman** [comment]
I didn't really have plans for April First to be more than some little joke project / test rollout. Adding the ability to repeat the joke / prank actually came out later when I had multiple people ask about that feature, and at that point it's quicker to just circulate the updated release package.

As for _Dreams and Nightmares_, I encourage you to make this suggestion there as well, because I had attempts to implement the Submod Updater there that didn't go as smoothly as I wanted them to go. I would _very_ much appreciate some assistance from someone who knows their way around that code and who might be able to tell me what it is that I'm doing wrong, but I'd like to keep any _Dreams and Nightmares_ issues on its own gitub.
